sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t  kaka120 / travis_test  -f Dockerfile.dev .

script:
  - docker run -e CI=true  kaka120 / travis_test  npm run test
